DELETE FROM DestinacijaAktivnost;
DELETE FROM DestinacijaVodic;
DELETE FROM Destinacija;
DELETE FROM Aktivnost;
DELETE FROM TuristickiVodic;
DELETE FROM Zemlja;
DELETE FROM VrstaPutovanja;
DELETE FROM Korisnik;

ALTER TABLE ZEMLJA ALTER COLUMN id RESTART WITH 1;
ALTER TABLE VRSTAPUTOVANJA ALTER COLUMN id RESTART WITH 1;
ALTER TABLE KORISNIK ALTER COLUMN id RESTART WITH 1;
ALTER TABLE AKTIVNOST ALTER COLUMN id RESTART WITH 1;
ALTER TABLE TURISTICKIVODIC ALTER COLUMN id RESTART WITH 1;
ALTER TABLE DESTINACIJA ALTER COLUMN id RESTART WITH 1;