INSERT INTO Zemlja(NAZIV, KOD_DRZAVE) VALUES ('Hrvatska', 'HR');
INSERT INTO Zemlja(NAZIV, KOD_DRZAVE) VALUES ('Italija', 'IT');
INSERT INTO Zemlja(NAZIV, KOD_DRZAVE) VALUES ('Francuska', 'FR');

INSERT INTO VRSTAPUTOVANJA(NAZIV) VALUES ('Avanturizam');
INSERT INTO VRSTAPUTOVANJA(NAZIV) VALUES ('Kulturni turizam');
INSERT INTO VRSTAPUTOVANJA(NAZIV) VALUES ('Plažni odmor');
INSERT INTO VRSTAPUTOVANJA(NAZIV) VALUES ('Gastronomski turizam');

INSERT INTO AKTIVNOST(NAZIV, OPIS) VALUES ('Ronjenje', 'Istraživanje podmorja');
INSERT INTO AKTIVNOST(NAZIV, OPIS) VALUES ('Planinarenje', 'Pješaćenje do vrha planine');
INSERT INTO AKTIVNOST(NAZIV, OPIS) VALUES ('Razgledavanje', 'Turistički obilazak');

INSERT INTO TURISTICKIVODIC(ime, prezime, kontakt) VALUES ('Marko', 'Markovic', 'marko@gmail.com');
INSERT INTO TURISTICKIVODIC(ime, prezime, kontakt) VALUES ('Pero', 'Peric', 'pero@gmail.com');

INSERT INTO DESTINACIJA(NAZIV, OPIS, LATITUDE, LONGITUDE, PREPORUCENOGODISNJEDOBA, PUTANJAFOTOGRAFIJA, ZEMLJAID, VRSTAPUTOVANJAID)
VALUES ( 'Dubrovnik', 'Biser Jadrana', 42.6507, 18.0122, 'Ljeto', '', 1, 3 );
INSERT INTO DESTINACIJA(NAZIV, OPIS, LATITUDE, LONGITUDE, PREPORUCENOGODISNJEDOBA, PUTANJAFOTOGRAFIJA, ZEMLJAID, VRSTAPUTOVANJAID)
VALUES ( 'Rim', 'Vječni grad', 41.9028, 12.4964, 'Proljeće', '', 2, 4 );

INSERT INTO DESTINACIJAAKTIVNOST(destinacijaid, aktivnostid) VALUES (1, 1);
INSERT INTO DESTINACIJAAKTIVNOST(destinacijaid, aktivnostid) VALUES (1, 3);
INSERT INTO DESTINACIJAAKTIVNOST(destinacijaid, aktivnostid) VALUES (2, 3);
